- name: Write nagios check command config.
  tags:
    - nrpe-external-master-relation-changed
    - upgrade-charm
  template:
    src: "check_name.cfg.jinja2"
    dest: "/etc/nagios/nrpe.d/{{ item.name }}.cfg"
    owner: nagios
    group: nagios
    mode: 0644
  when: relations['nrpe-external-master']
  loop: "{{ checks|flatten(levels=1) }}"
  notify:
    - nrpe config changes

- name: Write nagios check service definition for export.
  tags:
    - nrpe-external-master-relation-changed
    - upgrade-charm
    - config-changed
  template:
    src: "check_name_service_export.cfg.jinja2"
    dest: "/var/lib/nagios/export/service__{{ service_context }}_{{ unit_name }}_{{ item.name }}.cfg"
    owner: nagios
    group: nagios
    mode: 0644
  when: relations['nrpe-external-master']
  loop: "{{ checks|flatten(levels=1) }}"
  notify:
    - nrpe config changes
