- name: nrpe config changes
  command: >
    relation-set -r {{ item.__relid__ }}
    timestamp={{ ansible_date_time.iso8601_micro }}
  when: relations['nrpe-external-master']
  loop: "{{ relations['nrpe-external-master']|flatten(levels=1) }}"
